debug: false
spring:
    datasource:
        name: redpackage
        url: jdbc:mysql://127.0.0.1:3306/redpackage
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


#    data:
#        mongodb:
#            host: 192.168.56.103
#            port: 27018
#            database: account


#    rabbitmq:
#        host: 127.0.0.1
#        port: 5672
#        username: guest
#        password: guest


#    redis:
#        host: 120.26.202.89
#        port: 6379
#        password: 123456
#        pool:
#            max-active: 8
#            min-idle: 0
#            max-idle: 8
#            max-wait: 1


mybatis:
    mapper-locations: "classpath*:**/com.example.mapper/*.xml"


server:
    port: 8081




